// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using SqlkataWinFormsApp;

namespace RecordApp.Models
{
    public partial class ContactType
    {
        public ContactType()
        {
            Contacts = new List<Contact>();

        }

        public int ContactTypeIdentifier { get; set; }
        public string ContactTitle { get; set; }

        public virtual List<Contact> Contacts { get; set; }

    }
}