// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderDetailsStatusConsoleApp.Models
{
    public partial class OrderStatus
    {
        public OrderStatus()
        {
            OrderDetails = new HashSet<OrderDetails>();
        }

        public int StatusId { get; set; }
        public string Description { get; set; }

        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}