// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderDetailsStatusConsoleApp.Models
{
    public partial class Products
    {
        public Products()
        {
            OrderDetails = new HashSet<OrderDetails>();
        }

        /// <summary>
        /// This is the primary key for a single product
        /// </summary>
        public int ProductId { get; set; }
        /// <summary>
        /// This is the product name of the product
        /// </summary>
        public string ProductName { get; set; }
        public decimal? UnitPrice { get; set; }
        public short? UnitsInStock { get; set; }

        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}